### ISSUE TITLE
How to log in and original names

### ISSUE THREAD

**Issue by VanTuz5** [touno-io/hentai-downloader#11]
How to log in to the exhentai? And how to make the program download files with original names? And the pause button would not be in the way, because when the limit is reached, the program starts to cyclically try to continue downloading

**Comment by dvgamerr** [comment]
1. current version exhentai not supported.
2. The original names are not always sorted in the correct order after downloading.
3. it' not pause button but this is cancel button, there is still a bug.

**Comment by VanTuz5** [comment]
But when I download the galleries, it’s more convenient for me that the files have the original names

**Comment by dvgamerr** [comment]
but not me.
